version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
